env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'import/extensions': [1, { '.js', '.jsx', '.ts', '.tsx' }],
    'react/jsx-filename-extension':
      [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
    'no-unused-vars': 1,
    'react/function-component-definition': 0,
    'arrow-body-style': 0,
    'react/prop-types': 0,
    'react/jsx-no-useless-fragment': 0,
  }
